### ISSUE TITLE
How to Install

### ISSUE THREAD

**Issue by dalisoft** [browserify/browserify-website#41]
Shows Error:
`
Error: Cannot find module 'xml-parse-from-string' from 'C:\Users\Shavkatoff\svg'
    at C:\Users\Shavkatoff\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:46:17
    at process (C:\Users\Shavkatoff\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:173:43)
    at ondir (C:\Users\Shavkatoff\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:188:17)
    at load (C:\Users\Shavkatoff\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:69:43)
    at onex (C:\Users\Shavkatoff\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:92:31)
    at C:\Users\Shavkatoff\AppData\Roaming\npm\node_modules\browserify\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
`

Please, help me to install?

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant.
